Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Controllers\\AdminController",
            "name": "AdminController",
            "summary": "Class\u0020AdminController",
            "url": "classes/App-Controllers-AdminController.html"
        },                {
            "fqsen": "\\App\\Controllers\\AdminController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "initializes\u0020models\u0020and\u0020enforces\u0020security\u0020protocols",
            "url": "classes/App-Controllers-AdminController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\AdminController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "displays\u0020the\u0020dashboard\u0020with\u0020key\u0020performance\u0020indicators\u0020\u0028kpis\u0029",
            "url": "classes/App-Controllers-AdminController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\AdminController\u003A\u003Astats\u0028\u0029",
            "name": "stats",
            "summary": "renders\u0020the\u0020detailed\u0020statistics\u0020page",
            "url": "classes/App-Controllers-AdminController.html#method_stats"
        },                {
            "fqsen": "\\App\\Controllers\\AdminController\u003A\u003Asupplier\u0028\u0029",
            "name": "supplier",
            "summary": "retrieves\u0020and\u0020structures\u0020supplier\u0020orders\u0020for\u0020display",
            "url": "classes/App-Controllers-AdminController.html#method_supplier"
        },                {
            "fqsen": "\\App\\Controllers\\AdminController\u003A\u003ArunFactory\u0028\u0029",
            "name": "runFactory",
            "summary": "executes\u0020factory\u0020operations\u0020via\u0020the\u0020external\u0020java\u0020application",
            "url": "classes/App-Controllers-AdminController.html#method_runFactory"
        },                {
            "fqsen": "\\App\\Controllers\\AdminController\u003A\u003A\u0024admin_model",
            "name": "admin_model",
            "summary": "",
            "url": "classes/App-Controllers-AdminController.html#property_admin_model"
        },                {
            "fqsen": "\\App\\Controllers\\AdminController\u003A\u003A\u0024user_model",
            "name": "user_model",
            "summary": "",
            "url": "classes/App-Controllers-AdminController.html#property_user_model"
        },                {
            "fqsen": "\\App\\Controllers\\AdminController\u003A\u003A\u0024financial_model",
            "name": "financial_model",
            "summary": "",
            "url": "classes/App-Controllers-AdminController.html#property_financial_model"
        },                {
            "fqsen": "\\App\\Controllers\\AdminController\u003A\u003A\u0024stock_model",
            "name": "stock_model",
            "summary": "",
            "url": "classes/App-Controllers-AdminController.html#property_stock_model"
        },                {
            "fqsen": "\\App\\Controllers\\CartController",
            "name": "CartController",
            "summary": "Class\u0020CartController",
            "url": "classes/App-Controllers-CartController.html"
        },                {
            "fqsen": "\\App\\Controllers\\CartController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/App-Controllers-CartController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\CartController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Displays\u0020the\u0020cart\u0020contents\u0020and\u0020calculates\u0020totals",
            "url": "classes/App-Controllers-CartController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\CartController\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Adds\u0020a\u0020specific\u0020mosaic\u0020configuration\u0020to\u0020the\u0020cart",
            "url": "classes/App-Controllers-CartController.html#method_add"
        },                {
            "fqsen": "\\App\\Controllers\\CartController\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Removes\u0020a\u0020single\u0020item\u0020from\u0020the\u0020cart\u0020based\u0020on\u0020its\u0020unique\u0020id",
            "url": "classes/App-Controllers-CartController.html#method_remove"
        },                {
            "fqsen": "\\App\\Controllers\\CartController\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "Removes\u0020all\u0020items\u0020from\u0020the\u0020shopping\u0020cart",
            "url": "classes/App-Controllers-CartController.html#method_clear"
        },                {
            "fqsen": "\\App\\Controllers\\CartController\u003A\u003A\u0024translations",
            "name": "translations",
            "summary": "",
            "url": "classes/App-Controllers-CartController.html#property_translations"
        },                {
            "fqsen": "\\App\\Controllers\\CommandeController",
            "name": "CommandeController",
            "summary": "Class\u0020CommandeController",
            "url": "classes/App-Controllers-CommandeController.html"
        },                {
            "fqsen": "\\App\\Controllers\\CommandeController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initializes\u0020the\u0020controller\u0020and\u0020loads\u0020translation\u0020strings",
            "url": "classes/App-Controllers-CommandeController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\CommandeController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Displays\u0020a\u0020list\u0020of\u0020past\u0020orders\u0020for\u0020the\u0020authenticated\u0020user",
            "url": "classes/App-Controllers-CommandeController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\CommandeController\u003A\u003Adetail\u0028\u0029",
            "name": "detail",
            "summary": "Displays\u0020the\u0020detailed\u0020view\u0020of\u0020a\u0020specific\u0020order.",
            "url": "classes/App-Controllers-CommandeController.html#method_detail"
        },                {
            "fqsen": "\\App\\Controllers\\CommandeController\u003A\u003AdownloadCsv\u0028\u0029",
            "name": "downloadCsv",
            "summary": "Generates\u0020and\u0020forces\u0020download\u0020of\u0020a\u0020csv\u0020file\u0020containing\u0020the\u0020parts\u0020list",
            "url": "classes/App-Controllers-CommandeController.html#method_downloadCsv"
        },                {
            "fqsen": "\\App\\Controllers\\CommandeController\u003A\u003AdownloadImage\u0028\u0029",
            "name": "downloadImage",
            "summary": "Converts\u0020the\u0020stored\u0020base64\u0020string\u0020into\u0020a\u0020downloadable\u0020png\u0020image",
            "url": "classes/App-Controllers-CommandeController.html#method_downloadImage"
        },                {
            "fqsen": "\\App\\Controllers\\CommandeController\u003A\u003AdownloadPlan\u0028\u0029",
            "name": "downloadPlan",
            "summary": "Renders\u0020the\u0020printable\u0020assembly\u0020plan\u0020for\u0020a\u0020specific\u0020mosaic",
            "url": "classes/App-Controllers-CommandeController.html#method_downloadPlan"
        },                {
            "fqsen": "\\App\\Controllers\\CommandeController\u003A\u003AcheckAuth\u0028\u0029",
            "name": "checkAuth",
            "summary": "Helper\u0020to\u0020enforce\u0020authentication\u0020requirements",
            "url": "classes/App-Controllers-CommandeController.html#method_checkAuth"
        },                {
            "fqsen": "\\App\\Controllers\\CommandeController\u003A\u003A\u0024translations",
            "name": "translations",
            "summary": "",
            "url": "classes/App-Controllers-CommandeController.html#property_translations"
        },                {
            "fqsen": "\\App\\Controllers\\CompteController",
            "name": "CompteController",
            "summary": "Class\u0020CompteController",
            "url": "classes/App-Controllers-CompteController.html"
        },                {
            "fqsen": "\\App\\Controllers\\CompteController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initializes\u0020models\u0020and\u0020mailer\u0020services",
            "url": "classes/App-Controllers-CompteController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\CompteController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Displays\u0020the\u0020main\u0020user\u0020dashboard\u0020with\u0020profile\u0020details",
            "url": "classes/App-Controllers-CompteController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\CompteController\u003A\u003Aactiver\u0028\u0029",
            "name": "activer",
            "summary": "Triggers\u0020the\u0020account\u0020activation\u0020process\u0020for\u0020existing\u0020users",
            "url": "classes/App-Controllers-CompteController.html#method_activer"
        },                {
            "fqsen": "\\App\\Controllers\\CompteController\u003A\u003AsendVerificationEmail\u0028\u0029",
            "name": "sendVerificationEmail",
            "summary": "Dispatches\u0020the\u0020activation\u0020email\u0020via\u0020smtp",
            "url": "classes/App-Controllers-CompteController.html#method_sendVerificationEmail"
        },                {
            "fqsen": "\\App\\Controllers\\CompteController\u003A\u003A\u0024user_model",
            "name": "user_model",
            "summary": "",
            "url": "classes/App-Controllers-CompteController.html#property_user_model"
        },                {
            "fqsen": "\\App\\Controllers\\CompteController\u003A\u003A\u0024token_model",
            "name": "token_model",
            "summary": "",
            "url": "classes/App-Controllers-CompteController.html#property_token_model"
        },                {
            "fqsen": "\\App\\Controllers\\CompteController\u003A\u003A\u0024mail",
            "name": "mail",
            "summary": "",
            "url": "classes/App-Controllers-CompteController.html#property_mail"
        },                {
            "fqsen": "\\App\\Controllers\\CompteController\u003A\u003A\u0024translations",
            "name": "translations",
            "summary": "",
            "url": "classes/App-Controllers-CompteController.html#property_translations"
        },                {
            "fqsen": "\\App\\Controllers\\CropImagesController",
            "name": "CropImagesController",
            "summary": "Class\u0020CropImagesController",
            "url": "classes/App-Controllers-CropImagesController.html"
        },                {
            "fqsen": "\\App\\Controllers\\CropImagesController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initializes\u0020the\u0020controller\u0020and\u0020loads\u0020translation\u0020strings",
            "url": "classes/App-Controllers-CropImagesController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\CropImagesController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Displays\u0020the\u0020cropping\u0020interface\u0020for\u0020the\u0020most\u0020recently\u0020uploaded\u0020image",
            "url": "classes/App-Controllers-CropImagesController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\CropImagesController\u003A\u003Aprocess\u0028\u0029",
            "name": "process",
            "summary": "Handles\u0020the\u0020cropping\u0020logic\u0020by\u0020invoking\u0020an\u0020external\u0020java\u0020tool",
            "url": "classes/App-Controllers-CropImagesController.html#method_process"
        },                {
            "fqsen": "\\App\\Controllers\\CropImagesController\u003A\u003A\u0024translations",
            "name": "translations",
            "summary": "",
            "url": "classes/App-Controllers-CropImagesController.html#property_translations"
        },                {
            "fqsen": "\\App\\Controllers\\ImagesController",
            "name": "ImagesController",
            "summary": "Class\u0020ImagesController",
            "url": "classes/App-Controllers-ImagesController.html"
        },                {
            "fqsen": "\\App\\Controllers\\ImagesController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/App-Controllers-ImagesController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\ImagesController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "displays\u0020the\u0020landing\u0020page\u0020\u0028images\u0020view\u0029\n\u002A\u0020accessible\u0020to\u0020everyone\u0020\u0028public\u0020page\u0029\n\u002A\u0020view\u0020logic\u0020will\u0020determine\u0020if\u0020upload\u0020form\u0020is\u0020shown",
            "url": "classes/App-Controllers-ImagesController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\ImagesController\u003A\u003Aupload\u0028\u0029",
            "name": "upload",
            "summary": "handles\u0020file\u0020uploads\u0020via\u0020ajax\/post\n\u002A\u0020strictly\u0020restricted\u0020to\u0020logged\u002Din\u0020users\u0020with\u0020active\u0020accounts",
            "url": "classes/App-Controllers-ImagesController.html#method_upload"
        },                {
            "fqsen": "\\App\\Controllers\\ImagesController\u003A\u003Aview\u0028\u0029",
            "name": "view",
            "summary": "Retrieves\u0020and\u0020displays\u0020raw\u0020image\u0020data\u0020from\u0020the\u0020database.",
            "url": "classes/App-Controllers-ImagesController.html#method_view"
        },                {
            "fqsen": "\\App\\Controllers\\ImagesController\u003A\u003A\u0024translations",
            "name": "translations",
            "summary": "",
            "url": "classes/App-Controllers-ImagesController.html#property_translations"
        },                {
            "fqsen": "\\App\\Controllers\\PaymentController",
            "name": "PaymentController",
            "summary": "Class\u0020PaymentController",
            "url": "classes/App-Controllers-PaymentController.html"
        },                {
            "fqsen": "\\App\\Controllers\\PaymentController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/App-Controllers-PaymentController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\PaymentController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Displays\u0020the\u0020checkout\u0020page\u0020with\u0020cart\u0020summary\u0020and\u0020shipping\u0020details",
            "url": "classes/App-Controllers-PaymentController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\PaymentController\u003A\u003Aprocess\u0028\u0029",
            "name": "process",
            "summary": "Initiates\u0020the\u0020paypal\u0020payment\u0020flow\u0020by\u0020creating\u0020an\u0020order\u0020and\u0020redirecting\u0020the\u0020user",
            "url": "classes/App-Controllers-PaymentController.html#method_process"
        },                {
            "fqsen": "\\App\\Controllers\\PaymentController\u003A\u003Aconfirmation\u0028\u0029",
            "name": "confirmation",
            "summary": "Displays\u0020the\u0020final\u0020invoice\u0020and\u0020breakdown\u0020of\u0020costs\u0020after\u0020a\u0020successful\u0020purchase",
            "url": "classes/App-Controllers-PaymentController.html#method_confirmation"
        },                {
            "fqsen": "\\App\\Controllers\\PaymentController\u003A\u003AsendInvoiceEmail\u0028\u0029",
            "name": "sendInvoiceEmail",
            "summary": "Generates\u0020and\u0020dispatches\u0020the\u0020html\u0020receipt\u0020via\u0020smtp",
            "url": "classes/App-Controllers-PaymentController.html#method_sendInvoiceEmail"
        },                {
            "fqsen": "\\App\\Controllers\\PaymentController\u003A\u003Asuccess\u0028\u0029",
            "name": "success",
            "summary": "Handles\u0020the\u0020callback\u0020from\u0020paypal\u0020after\u0020user\u0020approval",
            "url": "classes/App-Controllers-PaymentController.html#method_success"
        },                {
            "fqsen": "\\App\\Controllers\\PaymentController\u003A\u003Acancel\u0028\u0029",
            "name": "cancel",
            "summary": "Handles\u0020cases\u0020where\u0020the\u0020user\u0020aborts\u0020the\u0020payment\u0020process\u0020at\u0020paypal",
            "url": "classes/App-Controllers-PaymentController.html#method_cancel"
        },                {
            "fqsen": "\\App\\Controllers\\PaymentController\u003A\u003AfinalizeOrder\u0028\u0029",
            "name": "finalizeOrder",
            "summary": "Persists\u0020the\u0020order\u0020to\u0020the\u0020database,\u0020generates\u0020final\u0020mosaic\u0020files,\u0020and\u0020updates\u0020stock",
            "url": "classes/App-Controllers-PaymentController.html#method_finalizeOrder"
        },                {
            "fqsen": "\\App\\Controllers\\PaymentController\u003A\u003AgetPayPalAccessToken\u0028\u0029",
            "name": "getPayPalAccessToken",
            "summary": "Retrieves\u0020a\u0020new\u0020oauth2\u0020access\u0020token\u0020from\u0020paypal",
            "url": "classes/App-Controllers-PaymentController.html#method_getPayPalAccessToken"
        },                {
            "fqsen": "\\App\\Controllers\\PaymentController\u003A\u003AcallPayPalApi\u0028\u0029",
            "name": "callPayPalApi",
            "summary": "Helper\u0020to\u0020execute\u0020curl\u0020requests\u0020against\u0020paypal\u0020api",
            "url": "classes/App-Controllers-PaymentController.html#method_callPayPalApi"
        },                {
            "fqsen": "\\App\\Controllers\\PaymentController\u003A\u003A\u0024translations",
            "name": "translations",
            "summary": "",
            "url": "classes/App-Controllers-PaymentController.html#property_translations"
        },                {
            "fqsen": "\\App\\Controllers\\PaymentController\u003A\u003A\u0024paypalBaseUrl",
            "name": "paypalBaseUrl",
            "summary": "",
            "url": "classes/App-Controllers-PaymentController.html#property_paypalBaseUrl"
        },                {
            "fqsen": "\\App\\Controllers\\ReviewImagesController",
            "name": "ReviewImagesController",
            "summary": "Class\u0020ReviewImagesController",
            "url": "classes/App-Controllers-ReviewImagesController.html"
        },                {
            "fqsen": "\\App\\Controllers\\ReviewImagesController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/App-Controllers-ReviewImagesController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\ReviewImagesController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Generates\u0020and\u0020displays\u0020mosaic\u0020previews\u0020with\u0020price\u0020calculations",
            "url": "classes/App-Controllers-ReviewImagesController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\ReviewImagesController\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Saves\u0020the\u0020selected\u0020mosaic\u0020configuration\u0020and\u0020redirects\u0020to\u0020payment",
            "url": "classes/App-Controllers-ReviewImagesController.html#method_save"
        },                {
            "fqsen": "\\App\\Controllers\\ReviewImagesController\u003A\u003A\u0024translations",
            "name": "translations",
            "summary": "",
            "url": "classes/App-Controllers-ReviewImagesController.html#property_translations"
        },                {
            "fqsen": "\\App\\Controllers\\SettingController",
            "name": "SettingController",
            "summary": "Class\u0020SettingController",
            "url": "classes/App-Controllers-SettingController.html"
        },                {
            "fqsen": "\\App\\Controllers\\SettingController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/App-Controllers-SettingController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\SettingController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Displays\u0020the\u0020settings\u0020page\u0020and\u0020handles\u0020theme\u0020switching\u0020logic",
            "url": "classes/App-Controllers-SettingController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\SettingController\u003A\u003AsetLanguage\u0028\u0029",
            "name": "setLanguage",
            "summary": "Updates\u0020the\u0020session\u0020language\u0020and\u0020redirects\u0020user\u0020back\u0020to\u0020previous\u0020page",
            "url": "classes/App-Controllers-SettingController.html#method_setLanguage"
        },                {
            "fqsen": "\\App\\Controllers\\SettingController\u003A\u003A\u0024translation_model",
            "name": "translation_model",
            "summary": "",
            "url": "classes/App-Controllers-SettingController.html#property_translation_model"
        },                {
            "fqsen": "\\App\\Controllers\\StockController",
            "name": "StockController",
            "summary": "Class\u0020StockController",
            "url": "classes/App-Controllers-StockController.html"
        },                {
            "fqsen": "\\App\\Controllers\\StockController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/App-Controllers-StockController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\StockController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Displays\u0020the\u0020paginated\u0020stock\u0020list\u0020with\u0020optional\u0020filters.",
            "url": "classes/App-Controllers-StockController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\StockController\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Handles\u0020stock\u0020adjustment\u0020form\u0020submissions.",
            "url": "classes/App-Controllers-StockController.html#method_add"
        },                {
            "fqsen": "\\App\\Controllers\\StockController\u003A\u003ArunJavaBuy\u0028\u0029",
            "name": "runJavaBuy",
            "summary": "Executes\u0020the\u0020external\u0020Java\u0020application\u0020to\u0020process\u0020a\u0020purchase.",
            "url": "classes/App-Controllers-StockController.html#method_runJavaBuy"
        },                {
            "fqsen": "\\App\\Controllers\\StockController\u003A\u003A\u0024stockModel",
            "name": "stockModel",
            "summary": "",
            "url": "classes/App-Controllers-StockController.html#property_stockModel"
        },                {
            "fqsen": "\\App\\Controllers\\UserController",
            "name": "UserController",
            "summary": "Class\u0020UserController",
            "url": "classes/App-Controllers-UserController.html"
        },                {
            "fqsen": "\\App\\Controllers\\UserController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/App-Controllers-UserController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\UserController\u003A\u003At\u0028\u0029",
            "name": "t",
            "summary": "Retrieves\u0020a\u0020translation\u0020for\u0020a\u0020given\u0020key",
            "url": "classes/App-Controllers-UserController.html#method_t"
        },                {
            "fqsen": "\\App\\Controllers\\UserController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Handles\u0020user\u0020login\u0020process\u0020with\u0020captcha\u0020and\u00202fa\u0020support",
            "url": "classes/App-Controllers-UserController.html#method_login"
        },                {
            "fqsen": "\\App\\Controllers\\UserController\u003A\u003Aadmin\u0028\u0029",
            "name": "admin",
            "summary": "Redirects\u0020authorized\u0020users\u0020to\u0020the\u0020admin\u0020dashboard",
            "url": "classes/App-Controllers-UserController.html#method_admin"
        },                {
            "fqsen": "\\App\\Controllers\\UserController\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Handles\u0020new\u0020user\u0020registration\u0020and\u0020validation\u0020email\u0020sending",
            "url": "classes/App-Controllers-UserController.html#method_register"
        },                {
            "fqsen": "\\App\\Controllers\\UserController\u003A\u003AresetPasswordForm\u0028\u0029",
            "name": "resetPasswordForm",
            "summary": "Processes\u0020the\u0020final\u0020password\u0020update\u0020after\u0020validation",
            "url": "classes/App-Controllers-UserController.html#method_resetPasswordForm"
        },                {
            "fqsen": "\\App\\Controllers\\UserController\u003A\u003AresetPassword\u0028\u0029",
            "name": "resetPassword",
            "summary": "Initiates\u0020the\u0020password\u0020reset\u0020flow\u0020by\u0020sending\u0020an\u0020email\u0020link",
            "url": "classes/App-Controllers-UserController.html#method_resetPassword"
        },                {
            "fqsen": "\\App\\Controllers\\UserController\u003A\u003Averify\u0028\u0029",
            "name": "verify",
            "summary": "Verifies\u0020tokens\u0020for\u0020account\u0020activation,\u0020password\u0020reset,\u0020or\u00202fa",
            "url": "classes/App-Controllers-UserController.html#method_verify"
        },                {
            "fqsen": "\\App\\Controllers\\UserController\u003A\u003AsendVerificationEmail\u0028\u0029",
            "name": "sendVerificationEmail",
            "summary": "Sends\u0020an\u0020email\u0020using\u0020smtp\u0020with\u0020mailjet\u0020configuration",
            "url": "classes/App-Controllers-UserController.html#method_sendVerificationEmail"
        },                {
            "fqsen": "\\App\\Controllers\\UserController\u003A\u003Atoggle2FA\u0028\u0029",
            "name": "toggle2FA",
            "summary": "Enables\u0020or\u0020disables\u00202fa\u0020for\u0020the\u0020current\u0020user",
            "url": "classes/App-Controllers-UserController.html#method_toggle2FA"
        },                {
            "fqsen": "\\App\\Controllers\\UserController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "Destroys\u0020user\u0020session\u0020and\u0020redirects\u0020to\u0020login",
            "url": "classes/App-Controllers-UserController.html#method_logout"
        },                {
            "fqsen": "\\App\\Controllers\\UserController\u003A\u003A\u0024user_model",
            "name": "user_model",
            "summary": "",
            "url": "classes/App-Controllers-UserController.html#property_user_model"
        },                {
            "fqsen": "\\App\\Controllers\\UserController\u003A\u003A\u0024token_model",
            "name": "token_model",
            "summary": "",
            "url": "classes/App-Controllers-UserController.html#property_token_model"
        },                {
            "fqsen": "\\App\\Controllers\\UserController\u003A\u003A\u0024mail",
            "name": "mail",
            "summary": "",
            "url": "classes/App-Controllers-UserController.html#property_mail"
        },                {
            "fqsen": "\\App\\Controllers\\UserController\u003A\u003A\u0024translations",
            "name": "translations",
            "summary": "",
            "url": "classes/App-Controllers-UserController.html#property_translations"
        },                {
            "fqsen": "\\App\\Core\\Controller",
            "name": "Controller",
            "summary": "Abstract\u0020Class\u0020Controller",
            "url": "classes/App-Core-Controller.html"
        },                {
            "fqsen": "\\App\\Core\\Controller\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/App-Core-Controller.html#method___construct"
        },                {
            "fqsen": "\\App\\Core\\Controller\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Renders\u0020a\u0020view\u0020file\u0020within\u0020a\u0020layout\u0020template.",
            "url": "classes/App-Core-Controller.html#method_render"
        },                {
            "fqsen": "\\App\\Core\\Controller\u003A\u003A\u0024trans",
            "name": "trans",
            "summary": "",
            "url": "classes/App-Core-Controller.html#property_trans"
        },                {
            "fqsen": "\\App\\Core\\Db",
            "name": "Db",
            "summary": "Class\u0020Db",
            "url": "classes/App-Core-Db.html"
        },                {
            "fqsen": "\\App\\Core\\Db\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Private\u0020constructor\u0020to\u0020prevent\u0020direct\u0020instantiation.",
            "url": "classes/App-Core-Db.html#method___construct"
        },                {
            "fqsen": "\\App\\Core\\Db\u003A\u003AgetInstance\u0028\u0029",
            "name": "getInstance",
            "summary": "Returns\u0020the\u0020single\u0020instance\u0020of\u0020the\u0020Database\u0020connection.",
            "url": "classes/App-Core-Db.html#method_getInstance"
        },                {
            "fqsen": "\\App\\Core\\Db\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "",
            "url": "classes/App-Core-Db.html#property_instance"
        },                {
            "fqsen": "\\App\\Core\\Main",
            "name": "Main",
            "summary": "Class\u0020main",
            "url": "classes/App-Core-Main.html"
        },                {
            "fqsen": "\\App\\Core\\Main\u003A\u003Astart\u0028\u0029",
            "name": "start",
            "summary": "Starts\u0020the\u0020application\u0020routing\u0020process.",
            "url": "classes/App-Core-Main.html#method_start"
        },                {
            "fqsen": "\\App\\Core\\Model",
            "name": "Model",
            "summary": "Class\u0020Model",
            "url": "classes/App-Core-Model.html"
        },                {
            "fqsen": "\\App\\Core\\Model\u003A\u003AfindAll\u0028\u0029",
            "name": "findAll",
            "summary": "Retrieves\u0020all\u0020records\u0020from\u0020the\u0020associated\u0020table.",
            "url": "classes/App-Core-Model.html#method_findAll"
        },                {
            "fqsen": "\\App\\Core\\Model\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Finds\u0020a\u0020specific\u0020record\u0020by\u0020its\u0020ID.",
            "url": "classes/App-Core-Model.html#method_find"
        },                {
            "fqsen": "\\App\\Core\\Model\u003A\u003Arequete\u0028\u0029",
            "name": "requete",
            "summary": "Executes\u0020a\u0020SQL\u0020query\u0020\u0028prepared\u0020or\u0020direct\u0029.",
            "url": "classes/App-Core-Model.html#method_requete"
        },                {
            "fqsen": "\\App\\Core\\Model\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Core-Model.html#property_table"
        },                {
            "fqsen": "\\App\\Core\\Model\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/App-Core-Model.html#property_db"
        },                {
            "fqsen": "\\App\\Models\\AdminModel",
            "name": "AdminModel",
            "summary": "Class\u0020AdminModel",
            "url": "classes/App-Models-AdminModel.html"
        },                {
            "fqsen": "\\App\\Models\\AdminModel\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/App-Models-AdminModel.html#method___construct"
        },                {
            "fqsen": "\\App\\Models\\AdminModel\u003A\u003AgetFactoryOrdersWithDetails\u0028\u0029",
            "name": "getFactoryOrdersWithDetails",
            "summary": "Retrieves\u0020detailed\u0020factory\u0020orders\u0020including\u0020item\u0020specifications",
            "url": "classes/App-Models-AdminModel.html#method_getFactoryOrdersWithDetails"
        },                {
            "fqsen": "\\App\\Models\\AdminModel\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/App-Models-AdminModel.html#property_db"
        },                {
            "fqsen": "\\App\\Models\\CommandeModel",
            "name": "CommandeModel",
            "summary": "Class\u0020CommandeModel",
            "url": "classes/App-Models-CommandeModel.html"
        },                {
            "fqsen": "\\App\\Models\\CommandeModel\u003A\u003AupdateStatus\u0028\u0029",
            "name": "updateStatus",
            "summary": "Updates\u0020the\u0020status\u0020of\u0020a\u0020specific\u0020order",
            "url": "classes/App-Models-CommandeModel.html#method_updateStatus"
        },                {
            "fqsen": "\\App\\Models\\CommandeModel\u003A\u003AgetOrderDetails\u0028\u0029",
            "name": "getOrderDetails",
            "summary": "Retrieves\u0020comprehensive\u0020order\u0020details\u0020including\u0020invoice\u0020and\u0020customer\u0020info",
            "url": "classes/App-Models-CommandeModel.html#method_getOrderDetails"
        },                {
            "fqsen": "\\App\\Models\\CommandeModel\u003A\u003AgetCommandeByUserId\u0028\u0029",
            "name": "getCommandeByUserId",
            "summary": "Fetches\u0020the\u0020order\u0020history\u0020for\u0020a\u0020logged\u002Din\u0020user",
            "url": "classes/App-Models-CommandeModel.html#method_getCommandeByUserId"
        },                {
            "fqsen": "\\App\\Models\\CommandeModel\u003A\u003AgetCommandeById\u0028\u0029",
            "name": "getCommandeById",
            "summary": "Retrieves\u0020a\u0020single\u0020order\u0020by\u0020its\u0020identifier",
            "url": "classes/App-Models-CommandeModel.html#method_getCommandeById"
        },                {
            "fqsen": "\\App\\Models\\CommandeModel\u003A\u003AgetCommandeStatusById\u0028\u0029",
            "name": "getCommandeStatusById",
            "summary": "Fetches\u0020the\u0020current\u0020status\u0020of\u0020an\u0020order",
            "url": "classes/App-Models-CommandeModel.html#method_getCommandeStatusById"
        },                {
            "fqsen": "\\App\\Models\\CommandeModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-CommandeModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\FinancialModel",
            "name": "FinancialModel",
            "summary": "Class\u0020FinancialModel",
            "url": "classes/App-Models-FinancialModel.html"
        },                {
            "fqsen": "\\App\\Models\\FinancialModel\u003A\u003AprocessOrder\u0028\u0029",
            "name": "processOrder",
            "summary": "Executes\u0020the\u0020complete\u0020checkout\u0020transaction\u0020in\u0020a\u0020safe,\u0020atomic\u0020manner",
            "url": "classes/App-Models-FinancialModel.html#method_processOrder"
        },                {
            "fqsen": "\\App\\Models\\FinancialModel\u003A\u003AgetTotalRevenue\u0028\u0029",
            "name": "getTotalRevenue",
            "summary": "Calculates\u0020total\u0020revenue\u0020from\u0020valid\u0020orders\u0020for\u0020admin\u0020kpis",
            "url": "classes/App-Models-FinancialModel.html#method_getTotalRevenue"
        },                {
            "fqsen": "\\App\\Models\\FinancialModel\u003A\u003AcountOrders\u0028\u0029",
            "name": "countOrders",
            "summary": "Counts\u0020total\u0020number\u0020of\u0020orders\u0020placed",
            "url": "classes/App-Models-FinancialModel.html#method_countOrders"
        },                {
            "fqsen": "\\App\\Models\\FinancialModel\u003A\u003AgetLastOrders\u0028\u0029",
            "name": "getLastOrders",
            "summary": "Retrieves\u0020the\u0020most\u0020recent\u0020orders\u0020for\u0020the\u0020admin\u0020dashboard",
            "url": "classes/App-Models-FinancialModel.html#method_getLastOrders"
        },                {
            "fqsen": "\\App\\Models\\ImagesModel",
            "name": "ImagesModel",
            "summary": "Class\u0020ImagesModel",
            "url": "classes/App-Models-ImagesModel.html"
        },                {
            "fqsen": "\\App\\Models\\ImagesModel\u003A\u003AsaveCustomerImage\u0028\u0029",
            "name": "saveCustomerImage",
            "summary": "Saves\u0020a\u0020new\u0020image\u0020by\u0020creating\u0020linked\u0020records\u0020in\u0020both\u0020image\u0020tables",
            "url": "classes/App-Models-ImagesModel.html#method_saveCustomerImage"
        },                {
            "fqsen": "\\App\\Models\\ImagesModel\u003A\u003AupdateCustomerImageBlob\u0028\u0029",
            "name": "updateCustomerImageBlob",
            "summary": "Updates\u0020the\u0020binary\u0020content\u0020of\u0020an\u0020existing\u0020image\u0020\u0028e.g.\u0020after\u0020cropping\u0029",
            "url": "classes/App-Models-ImagesModel.html#method_updateCustomerImageBlob"
        },                {
            "fqsen": "\\App\\Models\\ImagesModel\u003A\u003AgetImageById\u0028\u0029",
            "name": "getImageById",
            "summary": "Retrieves\u0020image\u0020data\u0020and\u0020metadata\u0020by\u0020id",
            "url": "classes/App-Models-ImagesModel.html#method_getImageById"
        },                {
            "fqsen": "\\App\\Models\\ImagesModel\u003A\u003AgetLastImageByUserId\u0028\u0029",
            "name": "getLastImageByUserId",
            "summary": "Fetches\u0020the\u0020most\u0020recently\u0020uploaded\u0020image\u0020for\u0020a\u0020specific\u0020user",
            "url": "classes/App-Models-ImagesModel.html#method_getLastImageByUserId"
        },                {
            "fqsen": "\\App\\Models\\ImagesModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-ImagesModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel",
            "name": "MosaicModel",
            "summary": "Class\u0020MosaicModel",
            "url": "classes/App-Models-MosaicModel.html"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AgenerateTemporaryMosaics\u0028\u0029",
            "name": "generateTemporaryMosaics",
            "summary": "Generates\u0020multiple\u0020mosaic\u0020variations\u0020\u0028e.g.,\u0020standard,\u0020optimized,\u0020stock\u002Dbased\u0029\nusing\u0020the\u0020external\u0020java\u0020engine",
            "url": "classes/App-Models-MosaicModel.html#method_generateTemporaryMosaics"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AsaveSelectedMosaic\u0028\u0029",
            "name": "saveSelectedMosaic",
            "summary": "Persists\u0020a\u0020selected\u0020mosaic\u0020configuration\u0020to\u0020the\u0020database",
            "url": "classes/App-Models-MosaicModel.html#method_saveSelectedMosaic"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AgetMosaicVisual\u0028\u0029",
            "name": "getMosaicVisual",
            "summary": "Generates\u0020a\u0020visual\u0020representation\u0020\u0028png\u0029\u0020of\u0020a\u0020stored\u0020mosaic",
            "url": "classes/App-Models-MosaicModel.html#method_getMosaicVisual"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AgetBricksList\u0028\u0029",
            "name": "getBricksList",
            "summary": "Parses\u0020mosaic\u0020content\u0020to\u0020produce\u0020a\u0020list\u0020of\u0020required\u0020bricks",
            "url": "classes/App-Models-MosaicModel.html#method_getBricksList"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AsaveMosaicComposition\u0028\u0029",
            "name": "saveMosaicComposition",
            "summary": "Converts\u0020the\u0020brick\u0020list\u0020into\u0020database\u0020records\u0020for\u0020order\u0020processing",
            "url": "classes/App-Models-MosaicModel.html#method_saveMosaicComposition"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AfindItemId\u0028\u0029",
            "name": "findItemId",
            "summary": "Resolves\u0020specific\u0020item\u0020id\u0020based\u0020on\u0020brick\u0020characteristics",
            "url": "classes/App-Models-MosaicModel.html#method_findItemId"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AhasComposition\u0028\u0029",
            "name": "hasComposition",
            "summary": "Checks\u0020if\u0020the\u0020composition\u0020\u0028recipe\u0029\u0020for\u0020a\u0020mosaic\u0020has\u0020already\u0020been\u0020saved",
            "url": "classes/App-Models-MosaicModel.html#method_hasComposition"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AgetMosaicPrice\u0028\u0029",
            "name": "getMosaicPrice",
            "summary": "Calculates\u0020the\u0020price\u0020of\u0020a\u0020stored\u0020mosaic\u0020based\u0020on\u0020its\u0020raw\u0020cost\u0020metadata",
            "url": "classes/App-Models-MosaicModel.html#method_getMosaicPrice"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AcalculatePriceFromContent\u0028\u0029",
            "name": "calculatePriceFromContent",
            "summary": "Calculates\u0020price\u0020directly\u0020from\u0020raw\u0020content\u0020string\u0020without\u0020db\u0020lookup",
            "url": "classes/App-Models-MosaicModel.html#method_calculatePriceFromContent"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AcountPiecesFromContent\u0028\u0029",
            "name": "countPiecesFromContent",
            "summary": "Counts\u0020total\u0020bricks\u0020required\u0020based\u0020on\u0020raw\u0020content",
            "url": "classes/App-Models-MosaicModel.html#method_countPiecesFromContent"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AgetMosaicsByOrderId\u0028\u0029",
            "name": "getMosaicsByOrderId",
            "summary": "Retrieves\u0020all\u0020mosaics\u0020associated\u0020with\u0020a\u0020specific\u0020order",
            "url": "classes/App-Models-MosaicModel.html#method_getMosaicsByOrderId"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AgetMosaicGridHtml\u0028\u0029",
            "name": "getMosaicGridHtml",
            "summary": "Generates\u0020html\u0020for\u0020a\u0020grid\u0020representation\u0020\u0028used\u0020for\u0020quick\u0020preview\u0029",
            "url": "classes/App-Models-MosaicModel.html#method_getMosaicGridHtml"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AgetMosaicPlanData\u0028\u0029",
            "name": "getMosaicPlanData",
            "summary": "Extracts\u0020detailed\u0020plan\u0020data\u0020for\u0020generating\u0020printable\u0020instructions",
            "url": "classes/App-Models-MosaicModel.html#method_getMosaicPlanData"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AupdateBriquesFile\u0028\u0029",
            "name": "updateBriquesFile",
            "summary": "Updates\u0020the\u0020temporary\u0020input\u0020file\u0020with\u0020current\u0020stock\u0020levels\u0020for\u0020java\u0020processing",
            "url": "classes/App-Models-MosaicModel.html#method_updateBriquesFile"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AdeductStockFromMosaic\u0028\u0029",
            "name": "deductStockFromMosaic",
            "summary": "Reduces\u0020inventory\u0020count\u0020when\u0020a\u0020mosaic\u0020is\u0020finalized",
            "url": "classes/App-Models-MosaicModel.html#method_deductStockFromMosaic"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AMARGIN_COEFF",
            "name": "MARGIN_COEFF",
            "summary": "",
            "url": "classes/App-Models-MosaicModel.html#constant_MARGIN_COEFF"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003AHANDLING_FEE",
            "name": "HANDLING_FEE",
            "summary": "",
            "url": "classes/App-Models-MosaicModel.html#constant_HANDLING_FEE"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003ADELIVERY_FEE",
            "name": "DELIVERY_FEE",
            "summary": "",
            "url": "classes/App-Models-MosaicModel.html#constant_DELIVERY_FEE"
        },                {
            "fqsen": "\\App\\Models\\MosaicModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-MosaicModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\StockModel",
            "name": "StockModel",
            "summary": "Class\u0020StockModel",
            "url": "classes/App-Models-StockModel.html"
        },                {
            "fqsen": "\\App\\Models\\StockModel\u003A\u003AgetPaginatedStock\u0028\u0029",
            "name": "getPaginatedStock",
            "summary": "Retrieves\u0020a\u0020paginated\u0020list\u0020of\u0020stock\u0020items\u0020with\u0020optional\u0020filters",
            "url": "classes/App-Models-StockModel.html#method_getPaginatedStock"
        },                {
            "fqsen": "\\App\\Models\\StockModel\u003A\u003AcountStockItems\u0028\u0029",
            "name": "countStockItems",
            "summary": "Counts\u0020total\u0020items\u0020matching\u0020the\u0020current\u0020filters\u0020for\u0020pagination",
            "url": "classes/App-Models-StockModel.html#method_countStockItems"
        },                {
            "fqsen": "\\App\\Models\\StockModel\u003A\u003AgetAllItemsForSearch\u0028\u0029",
            "name": "getAllItemsForSearch",
            "summary": "Retrieves\u0020all\u0020items\u0020formatted\u0020for\u0020a\u0020search\u0020dropdown",
            "url": "classes/App-Models-StockModel.html#method_getAllItemsForSearch"
        },                {
            "fqsen": "\\App\\Models\\StockModel\u003A\u003AgetAllShapes\u0028\u0029",
            "name": "getAllShapes",
            "summary": "Fetches\u0020distinct\u0020shapes\u0020for\u0020filter\u0020dropdowns",
            "url": "classes/App-Models-StockModel.html#method_getAllShapes"
        },                {
            "fqsen": "\\App\\Models\\StockModel\u003A\u003AgetAllColors\u0028\u0029",
            "name": "getAllColors",
            "summary": "Fetches\u0020distinct\u0020colors\u0020for\u0020filter\u0020dropdowns",
            "url": "classes/App-Models-StockModel.html#method_getAllColors"
        },                {
            "fqsen": "\\App\\Models\\StockModel\u003A\u003AupdateStock\u0028\u0029",
            "name": "updateStock",
            "summary": "Records\u0020a\u0020manual\u0020stock\u0020adjustment\u0020\u0028positive\u0020or\u0020negative\u0029",
            "url": "classes/App-Models-StockModel.html#method_updateStock"
        },                {
            "fqsen": "\\App\\Models\\StockModel\u003A\u003AcountLowStockItems\u0028\u0029",
            "name": "countLowStockItems",
            "summary": "Counts\u0020items\u0020below\u0020a\u0020certain\u0020stock\u0020threshold\u0020for\u0020dashboard\u0020alerts",
            "url": "classes/App-Models-StockModel.html#method_countLowStockItems"
        },                {
            "fqsen": "\\App\\Models\\StockModel\u003A\u003AgetFullStockDetails\u0028\u0029",
            "name": "getFullStockDetails",
            "summary": "Exports\u0020full\u0020inventory\u0020details\u0020for\u0020external\u0020processing\u0020or\u0020reporting",
            "url": "classes/App-Models-StockModel.html#method_getFullStockDetails"
        },                {
            "fqsen": "\\App\\Models\\StockModel\u003A\u003AgetItemReferenceById\u0028\u0029",
            "name": "getItemReferenceById",
            "summary": "Retrieves\u0020the\u0020text\u0020reference\u0020\u0028Shape\/Color\u0029\u0020expected\u0020by\u0020Java\u0020for\u0020a\u0020given\u0020ID.",
            "url": "classes/App-Models-StockModel.html#method_getItemReferenceById"
        },                {
            "fqsen": "\\App\\Models\\StockModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-StockModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\TokensModel",
            "name": "TokensModel",
            "summary": "Class\u0020TokensModel",
            "url": "classes/App-Models-TokensModel.html"
        },                {
            "fqsen": "\\App\\Models\\TokensModel\u003A\u003AgenerateToken\u0028\u0029",
            "name": "generateToken",
            "summary": "Generates\u0020a\u0020short\u002Dlived\u0020numeric\u0020token\u0020and\u0020stores\u0020it",
            "url": "classes/App-Models-TokensModel.html#method_generateToken"
        },                {
            "fqsen": "\\App\\Models\\TokensModel\u003A\u003AverifyToken\u0028\u0029",
            "name": "verifyToken",
            "summary": "Checks\u0020if\u0020a\u0020token\u0020exists\u0020and\u0020is\u0020still\u0020within\u0020its\u0020validity\u0020window",
            "url": "classes/App-Models-TokensModel.html#method_verifyToken"
        },                {
            "fqsen": "\\App\\Models\\TokensModel\u003A\u003AconsumeToken\u0028\u0029",
            "name": "consumeToken",
            "summary": "Removes\u0020a\u0020token\u0020permanently\u0020after\u0020successful\u0020use",
            "url": "classes/App-Models-TokensModel.html#method_consumeToken"
        },                {
            "fqsen": "\\App\\Models\\TokensModel\u003A\u003AdeleteToken\u0028\u0029",
            "name": "deleteToken",
            "summary": "Cleans\u0020up\u0020all\u0020expired\u0020tokens\u0020from\u0020the\u0020database",
            "url": "classes/App-Models-TokensModel.html#method_deleteToken"
        },                {
            "fqsen": "\\App\\Models\\TokensModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-TokensModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\TranslationModel",
            "name": "TranslationModel",
            "summary": "Class\u0020TranslationModel",
            "url": "classes/App-Models-TranslationModel.html"
        },                {
            "fqsen": "\\App\\Models\\TranslationModel\u003A\u003AgetTranslations\u0028\u0029",
            "name": "getTranslations",
            "summary": "Retrieves\u0020all\u0020translation\u0020pairs\u0020for\u0020a\u0020specific\u0020language",
            "url": "classes/App-Models-TranslationModel.html#method_getTranslations"
        },                {
            "fqsen": "\\App\\Models\\UsersModel",
            "name": "UsersModel",
            "summary": "Class\u0020UsersModel",
            "url": "classes/App-Models-UsersModel.html"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003AgetUserById\u0028\u0029",
            "name": "getUserById",
            "summary": "Retrieves\u0020full\u0020user\u0020profile\u0020by\u0020internal\u0020id",
            "url": "classes/App-Models-UsersModel.html#method_getUserById"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003AgetUserByUsername\u0028\u0029",
            "name": "getUserByUsername",
            "summary": "Retrieves\u0020user\u0020data\u0020by\u0020username\u0020for\u0020authentication",
            "url": "classes/App-Models-UsersModel.html#method_getUserByUsername"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003AgetEmailById\u0028\u0029",
            "name": "getEmailById",
            "summary": "Fetches\u0020only\u0020the\u0020email\u0020address\u0020for\u0020a\u0020specific\u0020user",
            "url": "classes/App-Models-UsersModel.html#method_getEmailById"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003AgetStatusById\u0028\u0029",
            "name": "getStatusById",
            "summary": "Checks\u0020the\u0020account\u0020status\u0020\u0028e.g.,\u0020active,\u0020banned,\u0020pending\u0029",
            "url": "classes/App-Models-UsersModel.html#method_getStatusById"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003AgetModeById\u0028\u0029",
            "name": "getModeById",
            "summary": "Retrieves\u0020the\u00202fa\u0020mode\u0020setting\u0020for\u0020the\u0020user",
            "url": "classes/App-Models-UsersModel.html#method_getModeById"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003AsetModeById\u0028\u0029",
            "name": "setModeById",
            "summary": "Updates\u0020the\u00202fa\u0020preference\u0020for\u0020a\u0020user",
            "url": "classes/App-Models-UsersModel.html#method_setModeById"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003AaddUser\u0028\u0029",
            "name": "addUser",
            "summary": "Registers\u0020a\u0020new\u0020user\u0020by\u0020creating\u0020records\u0020in\u0020both\u0020required\u0020tables",
            "url": "classes/App-Models-UsersModel.html#method_addUser"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003AactivateUser\u0028\u0029",
            "name": "activateUser",
            "summary": "Activates\u0020a\u0020user\u0020account\u0020after\u0020successful\u0020email\u0020verification",
            "url": "classes/App-Models-UsersModel.html#method_activateUser"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003AvalidateNewPassword\u0028\u0029",
            "name": "validateNewPassword",
            "summary": "Validates\u0020password\u0020complexity\u0020and\u0020history\u0020requirements",
            "url": "classes/App-Models-UsersModel.html#method_validateNewPassword"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003AupdatePassword\u0028\u0029",
            "name": "updatePassword",
            "summary": "Updates\u0020the\u0020user\u0027s\u0020password\u0020with\u0020a\u0020new\u0020hash",
            "url": "classes/App-Models-UsersModel.html#method_updatePassword"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003AgetUserByEmail\u0028\u0029",
            "name": "getUserByEmail",
            "summary": "Finds\u0020a\u0020user\u0020by\u0020email,\u0020used\u0020primarily\u0020for\u0020password\u0020reset\u0020requests",
            "url": "classes/App-Models-UsersModel.html#method_getUserByEmail"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003AcountUsers\u0028\u0029",
            "name": "countUsers",
            "summary": "Counts\u0020total\u0020registered\u0020standard\u0020users\u0020for\u0020admin\u0020statistics",
            "url": "classes/App-Models-UsersModel.html#method_countUsers"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-UsersModel.html#property_table"
        },                {
            "fqsen": "\\getStatusLink\u0028\u0029",
            "name": "getStatusLink",
            "summary": "",
            "url": "namespaces/default.html#function_getStatusLink"
        },                {
            "fqsen": "\\getPageLink\u0028\u0029",
            "name": "getPageLink",
            "summary": "",
            "url": "namespaces/default.html#function_getPageLink"
        },                {
            "fqsen": "\\ROOT",
            "name": "ROOT",
            "summary": "",
            "url": "namespaces/default.html#constant_ROOT"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-controllers.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Core",
            "name": "Core",
            "summary": "",
            "url": "namespaces/app-core.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        }            ]
);
